[project]
name = 'lynch-library'
requires-python = '>=3.12'
version = '0'

dependencies = [

    'aiohttp',

    'django',

    'django-storages[s3]',

]

[project.optional-dependencies]
pre-commit = [
    'actionlint-py',
    'basedpyright',
    'cookiecutter',
    'django-upgrade',
    'djlint',
    'factory-boy',
    'hadolint-py @ git+https://github.com/AleksaC/hadolint-py.git',
    'helicopyter @ git+https://github.com/biobuddies/helicopyter.git@0a5639d9b887d73d482950f5438a19dee751169c',
    'pre-commit-hooks',
    'pyrefly',
    'ruff',
    'shellcheck-py',
    'shfmt-py',
    'typos',
    'validate-pyproject[all]',
    'yamllint',
]
test = [
    'pytest',
    'pytest-cov',
    'pytest-django',
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'config.settings'
norecursedirs = ['.venv', 'node_modules', '{{cookiecutter.dot}}']

[tool.basedpyright]
extends = '.biobuddies/basedpyright.toml'

[tool.ruff]
extend = '.biobuddies/ruff.toml'
