"""Nominally cover autogenerated files.

AUTOGENERATED by https://github.com/biobuddies/measles
"""

from importlib import import_module

from pytest import MonkeyPatch


def test_manage_check(monkeypatch: MonkeyPatch):
    monkeypatch.setattr('sys.argv', ['/home/biobuddy/code/speedrun/manage.py', 'check'])
    import_module('manage').main()
